/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChannelsIndexRouteImport } from './routes/channels/index'
import { Route as CanvasIndexRouteImport } from './routes/canvas/index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/canvas/',
  path: '/canvas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/canvas/': typeof CanvasIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents': typeof AgentsIndexRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/canvas': typeof CanvasIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/config': typeof ConfigIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/models': typeof ModelsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/canvas/': typeof CanvasIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workflows/$workflowId'
    | '/agents/'
    | '/approvals/'
    | '/canvas/'
    | '/channels/'
    | '/chat/'
    | '/config/'
    | '/dashboard/'
    | '/events/'
    | '/memory/'
    | '/models/'
    | '/runs/'
    | '/schedule/'
    | '/templates/'
    | '/tools/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workflows/$workflowId'
    | '/agents'
    | '/approvals'
    | '/canvas'
    | '/channels'
    | '/chat'
    | '/config'
    | '/dashboard'
    | '/events'
    | '/memory'
    | '/models'
    | '/runs'
    | '/schedule'
    | '/templates'
    | '/tools'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/workflows/$workflowId'
    | '/agents/'
    | '/approvals/'
    | '/canvas/'
    | '/channels/'
    | '/chat/'
    | '/config/'
    | '/dashboard/'
    | '/events/'
    | '/memory/'
    | '/models/'
    | '/runs/'
    | '/schedule/'
    | '/templates/'
    | '/tools/'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/canvas'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  CanvasIndexRoute: CanvasIndexRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
