pub mod agent;
pub mod agents;
pub mod approval;
pub mod auth;
pub mod backup;
pub mod channel;
pub mod completions;
pub mod config;
pub mod conversation;
pub mod coordination;
pub mod cost;
#[cfg(feature = "tools-extended")]
pub mod cron;
pub mod daemon;
#[cfg(feature = "tui")]
pub mod dashboard;
#[cfg(feature = "tui")]
pub mod dashboard_tui;
pub mod doctor;
pub mod estop;
#[cfg(feature = "gateway")]
pub mod gateway;
pub mod goals;
pub mod hardware;
pub mod hooks;
pub mod identity;
pub mod integrations;
pub mod local;
pub mod mcp_serve;
pub mod memory;
pub mod models;
pub mod onboard;
pub mod peripheral;
#[cfg(feature = "plugins")]
pub mod plugin;
pub mod privacy;
pub mod providers;
pub mod rag;
pub mod sandbox;
pub mod service;
#[cfg(feature = "tools-extended")]
pub mod skill;
pub mod status;
pub mod swarm;
pub mod template;
pub mod tools;
pub mod tunnel;
pub mod update;
#[cfg(feature = "interactive")]
pub mod ux;
pub mod workflow;
