#!/usr/bin/env python3
"""Convert security-policy.yaml to iptables rules for sandbox network isolation.

Reads the AgentZero security-policy.yaml and emits iptables rules that:
- Default DROP on OUTPUT chain
- Allow DNS (UDP/TCP 53)
- Allow loopback traffic
- Allow ESTABLISHED/RELATED return traffic
- Allow egress to each domain listed in tool rules
"""

import socket
import sys

try:
    import yaml
except ImportError:
    # Fallback: minimal YAML parser for the subset we need
    yaml = None


def parse_yaml_minimal(path):
    """Minimal parser that extracts allowed_domains from egress lists.

    This handles the simple case where yaml module is not installed.
    """
    domains = []
    with open(path, "r") as f:
        for line in f:
            stripped = line.strip()
            # Look for egress list entries like "- api.openai.com"
            if stripped.startswith("- ") and "." in stripped:
                value = stripped[2:].strip().strip('"').strip("'")
                # Skip glob entries and special values
                if value.startswith("*") or value in ("prompt", "allow", "deny"):
                    continue
                # Basic domain validation
                if all(c.isalnum() or c in ".-" for c in value) and "." in value:
                    domains.append(value)
    return domains


def parse_yaml_full(path):
    """Full parser using PyYAML."""
    with open(path, "r") as f:
        policy = yaml.safe_load(f)

    domains = []
    for rule in policy.get("rules", []):
        for entry in rule.get("egress", []):
            if entry in ("prompt",):
                continue
            # Skip wildcard entries (iptables works with IPs)
            if entry.startswith("*."):
                continue
            domains.append(entry)
    return domains


def resolve_domain(domain):
    """Resolve a domain to its IP addresses."""
    ips = []
    try:
        results = socket.getaddrinfo(domain, None, socket.AF_INET)
        for result in results:
            ip = result[4][0]
            if ip not in ips:
                ips.append(ip)
    except socket.gaierror:
        print(f"# Warning: could not resolve {domain}", file=sys.stderr)
    return ips


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <security-policy.yaml>", file=sys.stderr)
        sys.exit(1)

    policy_path = sys.argv[1]

    if yaml is not None:
        domains = parse_yaml_full(policy_path)
    else:
        domains = parse_yaml_minimal(policy_path)

    # Emit iptables rules
    print("# Auto-generated by policy-to-iptables.py")
    print("# Flush existing OUTPUT rules")
    print("-F OUTPUT")
    print()

    # Allow loopback
    print("# Allow loopback")
    print("-A OUTPUT -o lo -j ACCEPT")
    print()

    # Allow established/related connections
    print("# Allow established and related connections")
    print("-A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT")
    print()

    # Allow DNS
    print("# Allow DNS resolution")
    print("-A OUTPUT -p udp --dport 53 -j ACCEPT")
    print("-A OUTPUT -p tcp --dport 53 -j ACCEPT")
    print()

    # Allow each resolved domain
    seen_ips = set()
    for domain in domains:
        ips = resolve_domain(domain)
        for ip in ips:
            if ip not in seen_ips:
                seen_ips.add(ip)
                print(f"# {domain}")
                print(f"-A OUTPUT -d {ip} -j ACCEPT")
    print()

    # Default DROP
    print("# Default DROP for all other outbound traffic")
    print("-P OUTPUT DROP")


if __name__ == "__main__":
    main()
