//! Dynamic per-project tool registration with versioning.
//!
//! Manages WASM tools generated at runtime by the self-improving agent loop.
//! Tools are stored per-project in `.agentzero/skills/<name>/v<N>/` with
//! directory-based versioning and an `active.json` pointer (ADR 0012).

use std::path::{Path, PathBuf};

use agentzero_tracing::{info, warn};
use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum DynamicToolError {
    #[error("IO error: {0}")]
    Io(String),
    #[error("tool already exists at version {version}: {name}")]
    AlreadyExists { name: String, version: u32 },
    #[error("tool not found: {0}")]
    NotFound(String),
    #[error("no active version for tool: {0}")]
    NoActiveVersion(String),
    #[error("serialization error: {0}")]
    Serialization(String),
}

/// Pointer to the active version of a dynamic tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActiveVersion {
    pub active: u32,
}

/// Metadata for a registered dynamic tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DynamicToolEntry {
    pub name: String,
    pub description: String,
    pub version: u32,
    pub template: String,
    pub wasm_size: usize,
    pub created: String,
}

/// Manages dynamic tool storage under `.agentzero/skills/`.
pub struct DynamicToolRegistry {
    skills_dir: PathBuf,
}

impl DynamicToolRegistry {
    /// Create a registry rooted at a project's `.agentzero/skills/` directory.
    pub fn new(project_root: &Path) -> Self {
        Self {
            skills_dir: project_root.join(".agentzero").join("skills"),
        }
    }

    /// Register a new tool version, storing WASM bytes and manifest.
    ///
    /// Returns the version number assigned. If the tool already exists,
    /// creates a new version directory (v2, v3, ...) and updates `active.json`.
    pub fn register(
        &self,
        name: &str,
        description: &str,
        template: &str,
        wasm_bytes: &[u8],
    ) -> Result<u32, DynamicToolError> {
        let tool_dir = self.skills_dir.join(name);
        let version = self.next_version(name);
        let version_dir = tool_dir.join(format!("v{version}"));

        info!(
            tool = name,
            version = version,
            bytes = wasm_bytes.len(),
            "registering dynamic tool"
        );

        // Create version directory
        std::fs::create_dir_all(&version_dir).map_err(|e| {
            DynamicToolError::Io(format!("failed to create {}: {e}", version_dir.display()))
        })?;

        // Write WASM module
        let wasm_path = version_dir.join("tool.wasm");
        std::fs::write(&wasm_path, wasm_bytes).map_err(|e| {
            DynamicToolError::Io(format!("failed to write {}: {e}", wasm_path.display()))
        })?;

        // Write SKILL.md manifest
        let timestamp = chrono::Utc::now().to_rfc3339();
        let manifest = format!(
            "---\nid: {name}\nname: {name}\nversion: 0.{version}.0\n\
             description: \"{description}\"\nruntime: wasm\ntrust: untrusted\n\
             template: {template}\ncreated: {timestamp}\n---\n\n\
             # {name}\n\n{description}\n\nGenerated by AgentZero self-improving agent.\n"
        );
        let manifest_path = version_dir.join("SKILL.md");
        std::fs::write(&manifest_path, manifest).map_err(|e| {
            DynamicToolError::Io(format!("failed to write {}: {e}", manifest_path.display()))
        })?;

        // Write lockfile entry for this version
        let entry = DynamicToolEntry {
            name: name.to_string(),
            description: description.to_string(),
            version,
            template: template.to_string(),
            wasm_size: wasm_bytes.len(),
            created: timestamp,
        };
        let entry_path = version_dir.join("entry.json");
        let entry_json = serde_json::to_string_pretty(&entry)
            .map_err(|e| DynamicToolError::Serialization(e.to_string()))?;
        std::fs::write(&entry_path, entry_json).map_err(|e| {
            DynamicToolError::Io(format!("failed to write {}: {e}", entry_path.display()))
        })?;

        // Update active.json pointer
        let active = ActiveVersion { active: version };
        let active_path = tool_dir.join("active.json");
        let active_json = serde_json::to_string_pretty(&active)
            .map_err(|e| DynamicToolError::Serialization(e.to_string()))?;
        std::fs::write(&active_path, active_json).map_err(|e| {
            DynamicToolError::Io(format!("failed to write {}: {e}", active_path.display()))
        })?;

        info!(
            tool = name,
            version = version,
            path = %version_dir.display(),
            "dynamic tool registered"
        );

        Ok(version)
    }

    /// Load the WASM bytes for a tool's active version.
    pub fn load_active(&self, name: &str) -> Result<Vec<u8>, DynamicToolError> {
        let tool_dir = self.skills_dir.join(name);
        let active_path = tool_dir.join("active.json");

        if !active_path.exists() {
            return Err(DynamicToolError::NotFound(name.to_string()));
        }

        let active_json = std::fs::read_to_string(&active_path)
            .map_err(|e| DynamicToolError::Io(e.to_string()))?;
        let active: ActiveVersion = serde_json::from_str(&active_json)
            .map_err(|e| DynamicToolError::Serialization(e.to_string()))?;

        let wasm_path = tool_dir
            .join(format!("v{}", active.active))
            .join("tool.wasm");
        if !wasm_path.exists() {
            return Err(DynamicToolError::NotFound(format!(
                "{name} v{} wasm not found",
                active.active
            )));
        }

        std::fs::read(&wasm_path).map_err(|e| DynamicToolError::Io(e.to_string()))
    }

    /// Get the active version number for a tool, or None if not registered.
    pub fn active_version(&self, name: &str) -> Option<u32> {
        let active_path = self.skills_dir.join(name).join("active.json");
        let content = std::fs::read_to_string(&active_path).ok()?;
        let active: ActiveVersion = serde_json::from_str(&content).ok()?;
        Some(active.active)
    }

    /// Rollback a tool to a previous version.
    pub fn rollback(&self, name: &str, version: u32) -> Result<(), DynamicToolError> {
        let tool_dir = self.skills_dir.join(name);
        let version_dir = tool_dir.join(format!("v{version}"));

        if !version_dir.exists() {
            return Err(DynamicToolError::NotFound(format!(
                "{name} v{version} does not exist"
            )));
        }

        warn!(tool = name, version = version, "rolling back dynamic tool");

        let active = ActiveVersion { active: version };
        let active_path = tool_dir.join("active.json");
        let active_json = serde_json::to_string_pretty(&active)
            .map_err(|e| DynamicToolError::Serialization(e.to_string()))?;
        std::fs::write(&active_path, active_json).map_err(|e| DynamicToolError::Io(e.to_string()))
    }

    /// List all registered dynamic tools.
    pub fn list(&self) -> Result<Vec<String>, DynamicToolError> {
        if !self.skills_dir.exists() {
            return Ok(vec![]);
        }

        let mut tools = Vec::new();
        let entries =
            std::fs::read_dir(&self.skills_dir).map_err(|e| DynamicToolError::Io(e.to_string()))?;

        for entry in entries.flatten() {
            if entry.path().is_dir() {
                let active_path = entry.path().join("active.json");
                if active_path.exists() {
                    if let Some(name) = entry.file_name().to_str() {
                        tools.push(name.to_string());
                    }
                }
            }
        }

        tools.sort();
        Ok(tools)
    }

    fn next_version(&self, name: &str) -> u32 {
        self.active_version(name).map_or(1, |v| v + 1)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_registry() -> (tempfile::TempDir, DynamicToolRegistry) {
        let dir = tempfile::tempdir().expect("temp dir");
        let registry = DynamicToolRegistry::new(dir.path());
        (dir, registry)
    }

    #[test]
    fn register_creates_version_directory() {
        let (_dir, registry) = temp_registry();
        let version = registry
            .register("test-tool", "A test tool", "pure_computation", b"fake wasm")
            .expect("should register");
        assert_eq!(version, 1);

        // Verify files exist
        let tool_dir = registry.skills_dir.join("test-tool");
        assert!(tool_dir.join("active.json").exists());
        assert!(tool_dir.join("v1").join("tool.wasm").exists());
        assert!(tool_dir.join("v1").join("SKILL.md").exists());
        assert!(tool_dir.join("v1").join("entry.json").exists());
    }

    #[test]
    fn register_increments_version() {
        let (_dir, registry) = temp_registry();
        let v1 = registry
            .register("tool", "v1", "logger", b"wasm v1")
            .expect("v1");
        let v2 = registry
            .register("tool", "v2", "logger", b"wasm v2")
            .expect("v2");
        assert_eq!(v1, 1);
        assert_eq!(v2, 2);
        assert_eq!(registry.active_version("tool"), Some(2));
    }

    #[test]
    fn load_active_returns_latest_bytes() {
        let (_dir, registry) = temp_registry();
        registry
            .register("tool", "first", "pure", b"wasm-v1")
            .expect("v1");
        registry
            .register("tool", "second", "pure", b"wasm-v2")
            .expect("v2");

        let bytes = registry.load_active("tool").expect("should load");
        assert_eq!(bytes, b"wasm-v2");
    }

    #[test]
    fn rollback_changes_active_version() {
        let (_dir, registry) = temp_registry();
        registry
            .register("tool", "first", "pure", b"wasm-v1")
            .expect("v1");
        registry
            .register("tool", "second", "pure", b"wasm-v2")
            .expect("v2");

        registry.rollback("tool", 1).expect("should rollback");
        assert_eq!(registry.active_version("tool"), Some(1));

        let bytes = registry.load_active("tool").expect("should load");
        assert_eq!(bytes, b"wasm-v1");
    }

    #[test]
    fn rollback_nonexistent_version_fails() {
        let (_dir, registry) = temp_registry();
        registry
            .register("tool", "desc", "pure", b"wasm")
            .expect("v1");
        let result = registry.rollback("tool", 99);
        assert!(result.is_err());
    }

    #[test]
    fn load_active_nonexistent_tool_fails() {
        let (_dir, registry) = temp_registry();
        let result = registry.load_active("nonexistent");
        assert!(result.is_err());
    }

    #[test]
    fn list_returns_registered_tools() {
        let (_dir, registry) = temp_registry();
        registry
            .register("alpha", "desc", "pure", b"wasm")
            .expect("alpha");
        registry
            .register("beta", "desc", "pure", b"wasm")
            .expect("beta");

        let tools = registry.list().expect("should list");
        assert_eq!(tools, vec!["alpha", "beta"]);
    }

    #[test]
    fn list_empty_when_no_tools() {
        let (_dir, registry) = temp_registry();
        let tools = registry.list().expect("should list");
        assert!(tools.is_empty());
    }

    #[test]
    fn active_version_none_for_unknown() {
        let (_dir, registry) = temp_registry();
        assert_eq!(registry.active_version("unknown"), None);
    }
}
