//! Implementation of the `#[tool(name = "...", description = "...")]` attribute macro.

use proc_macro::TokenStream;
use quote::quote;
use syn::parse::{Parse, ParseStream};
use syn::{parse_macro_input, Ident, LitStr, Token};

struct ToolArgs {
    name: LitStr,
    description: LitStr,
}

impl Parse for ToolArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut name: Option<LitStr> = None;
        let mut description: Option<LitStr> = None;

        while !input.is_empty() {
            let key: Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let value: LitStr = input.parse()?;

            match key.to_string().as_str() {
                "name" => name = Some(value),
                "description" => description = Some(value),
                other => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!(
                            "unknown tool attribute: `{other}` (expected `name` or `description`)"
                        ),
                    ))
                }
            }

            if !input.is_empty() {
                input.parse::<Token![,]>()?;
            }
        }

        let name = name.ok_or_else(|| input.error("missing `name` attribute"))?;
        let description =
            description.ok_or_else(|| input.error("missing `description` attribute"))?;

        Ok(ToolArgs { name, description })
    }
}

pub fn expand(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as ToolArgs);
    let item = parse_macro_input!(item as syn::Item);

    let struct_item = match &item {
        syn::Item::Struct(s) => s,
        _ => {
            return syn::Error::new_spanned(&item, "#[tool] can only be applied to structs")
                .to_compile_error()
                .into();
        }
    };

    let struct_name = &struct_item.ident;
    let tool_name = &args.name;
    let tool_description = &args.description;

    let expanded = quote! {
        #item

        impl #struct_name {
            /// Returns the tool name as a static string (generated by `#[tool]`).
            pub const fn tool_name() -> &'static str {
                #tool_name
            }

            /// Returns the tool description as a static string (generated by `#[tool]`).
            pub const fn tool_description() -> &'static str {
                #tool_description
            }
        }
    };

    expanded.into()
}
