//! Implementation of `#[derive(ToolSchema)]` — generates JSON Schema from struct fields.

use quote::quote;
use syn::{Attribute, DeriveInput, Fields, Lit, LitStr, Meta, Type};

pub fn expand(input: DeriveInput) -> proc_macro::TokenStream {
    let struct_name = &input.ident;

    let fields = match &input.data {
        syn::Data::Struct(data) => &data.fields,
        _ => {
            return syn::Error::new_spanned(&input, "ToolSchema can only be derived for structs")
                .to_compile_error()
                .into();
        }
    };

    let named_fields = match fields {
        Fields::Named(named) => &named.named,
        _ => {
            return syn::Error::new_spanned(
                &input,
                "ToolSchema requires named fields (not tuple or unit structs)",
            )
            .to_compile_error()
            .into();
        }
    };

    let mut property_entries = Vec::new();
    let mut required_entries = Vec::new();

    for field in named_fields {
        let field_name = field
            .ident
            .as_ref()
            .expect("named fields should have identifiers");
        let field_name_str = field_name.to_string();

        let doc_description = extract_doc_comment(&field.attrs);
        let enum_values = extract_schema_enum_values(&field.attrs);
        let items_type_override = extract_schema_items_type(&field.attrs);
        let has_serde_default = has_serde_default_attr(&field.attrs);

        let (json_type, is_optional, is_array) = rust_type_to_json_type(&field.ty);

        // Build the property object tokens
        let type_token = quote! { "type": #json_type };

        let desc_token = if let Some(desc) = &doc_description {
            quote! { , "description": #desc }
        } else {
            quote! {}
        };

        let enum_token = if let Some(vals) = &enum_values {
            let val_tokens: Vec<_> = vals.iter().map(|v| quote! { #v }).collect();
            quote! { , "enum": [#(#val_tokens),*] }
        } else {
            quote! {}
        };

        let items_token = if is_array {
            let items_type = items_type_override.as_deref().unwrap_or("string");
            quote! { , "items": { "type": #items_type } }
        } else {
            quote! {}
        };

        property_entries.push(quote! {
            #field_name_str: {
                #type_token
                #desc_token
                #enum_token
                #items_token
            }
        });

        if !is_optional && !has_serde_default {
            required_entries.push(quote! { #field_name_str });
        }
    }

    let expanded = quote! {
        impl #struct_name {
            /// Returns the JSON Schema for this input struct (generated by `ToolSchema`).
            pub fn schema() -> serde_json::Value {
                serde_json::json!({
                    "type": "object",
                    "properties": {
                        #(#property_entries),*
                    },
                    "required": [#(#required_entries),*]
                })
            }
        }
    };

    expanded.into()
}

/// Extract doc comments from attributes and join them into a single description string.
pub(crate) fn extract_doc_comment(attrs: &[Attribute]) -> Option<String> {
    let docs: Vec<String> = attrs
        .iter()
        .filter_map(|attr| {
            if !attr.path().is_ident("doc") {
                return None;
            }
            if let Meta::NameValue(nv) = &attr.meta {
                if let syn::Expr::Lit(expr_lit) = &nv.value {
                    if let Lit::Str(lit_str) = &expr_lit.lit {
                        return Some(lit_str.value().trim().to_string());
                    }
                }
            }
            None
        })
        .filter(|s| !s.is_empty())
        .collect();

    if docs.is_empty() {
        None
    } else {
        Some(docs.join(" "))
    }
}

/// Extract `#[schema(enum_values = ["a", "b", "c"])]` from field attributes.
pub(crate) fn extract_schema_enum_values(attrs: &[Attribute]) -> Option<Vec<String>> {
    for attr in attrs {
        if !attr.path().is_ident("schema") {
            continue;
        }
        let mut result = None;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("enum_values") {
                meta.input.parse::<syn::Token![=]>()?;
                let content;
                syn::bracketed!(content in meta.input);
                let mut values = Vec::new();
                while !content.is_empty() {
                    let lit: LitStr = content.parse()?;
                    values.push(lit.value());
                    if !content.is_empty() {
                        content.parse::<syn::Token![,]>()?;
                    }
                }
                result = Some(values);
            }
            Ok(())
        });
        if result.is_some() {
            return result;
        }
    }
    None
}

/// Extract `#[schema(items_type = "string")]` from field attributes.
pub(crate) fn extract_schema_items_type(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("schema") {
            continue;
        }
        let mut result = None;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("items_type") {
                let value = meta.value()?;
                let lit: LitStr = value.parse()?;
                result = Some(lit.value());
            }
            Ok(())
        });
        if result.is_some() {
            return result;
        }
    }
    None
}

/// Check if the field has `#[serde(default)]`.
pub(crate) fn has_serde_default_attr(attrs: &[Attribute]) -> bool {
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let mut found = false;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("default") {
                found = true;
            }
            Ok(())
        });
        if found {
            return true;
        }
    }
    false
}

/// Map a Rust type to a JSON Schema type string.
/// Returns (json_type, is_optional, is_array).
pub(crate) fn rust_type_to_json_type(ty: &Type) -> (&'static str, bool, bool) {
    if let Type::Path(type_path) = ty {
        let segments = &type_path.path.segments;
        if let Some(last) = segments.last() {
            let ident = last.ident.to_string();

            // Check for Option<T> — extract inner type
            if ident == "Option" {
                if let syn::PathArguments::AngleBracketed(args) = &last.arguments {
                    if let Some(syn::GenericArgument::Type(inner)) = args.args.first() {
                        let (inner_type, _, is_array) = rust_type_to_json_type(inner);
                        return (inner_type, true, is_array);
                    }
                }
                return ("string", true, false);
            }

            // Check for Vec<T>
            if ident == "Vec" {
                return ("array", false, true);
            }

            // Primitive types
            return match ident.as_str() {
                "String" | "str" => ("string", false, false),
                "bool" => ("boolean", false, false),
                "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "i8" | "i16" | "i32" | "i64"
                | "i128" | "isize" => ("integer", false, false),
                "f32" | "f64" => ("number", false, false),
                "Value" => ("object", false, false),
                _ => ("string", false, false),
            };
        }
    }
    ("string", false, false)
}
